spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: aiuser
    password: aisecret
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: gpt-oss:20b
          temperature: 0.7
    vertex:
      ai:
        project-id: ${GEMINI_PROJECT_ID}
        location: ${GEMINI_LOCATION}
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
          chat:
            options:
              model: gemini-2.5-flash
              temperature: 0.7
        embedding:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
          options:
            model: text-embedding-004